### ISSUE TITLE
No items in web interface

### ISSUE THREAD

**Issue by sevenpoundowl** [nuc/Midi-Connector#4]
Nothing shows up on the web interface despite aconnect -l showing a list of items.

![image](https://user-images.githubusercontent.com/8853603/54390723-6c57aa00-4660-11e9-85f0-6829f17ded9e.png)

```
pi@raspberrypi:~ $ aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'USB MIDI Controller' [type=kernel,card=1]
    0 'USB MIDI Controller MIDI 1'
client 24: 'USB MIDI Interface' [type=kernel,card=2]
    0 'USB MIDI Interface MIDI 1'
```

**Comment by nuc** [comment]
Can you try to visit http://raspberrypi.local:3000/midi-devices with Chrome and check the output?

Also, if the devices are connected after booting up, you might need to reload the app - either refresh the browser or click on the "Midi Connector".

**Comment by nuc** [comment]
That's my `midi-devices` output, for comparison:

```
[
  {
    name: "System",
    clientId: 0,
    ports: [
      {
        portName: "Timer",
        portId: 0,
        connectingTo: null,
        connectedFrom: null
      },
      {
        portName: "Announce",
        portId: 1,
        connectingTo: null,
        connectedFrom: null
      }
    ]
  },
  {
    name: "Midi Through",
    clientId: 14,
    ports: [
      {
        portName: "Midi Through Port-0",
        portId: 0,
        connectingTo: null,
        connectedFrom: null
      }
    ]
  },
  {
    name: "USB MIDI Interface",
    clientId: 20,
    ports: [
      {
        portName: "USB MIDI Interface MIDI 1",
        portId: 0,
        connectingTo: null,
        connectedFrom: null
      }
    ]
  }
]
```

**Comment by nuc** [comment]
Ah, the "Midi Connector" link was pointing to the wrong place. 

I just fixed that, please pull the latest version :)

**Comment by sevenpoundowl** [comment]
I've tried reloading the app with no success.

Here is the output from the midi-devices page:

"[{"name":"System","clientId":0,"ports":[{"portName":"Timer","portId":0,"connectingTo":null,"connectedFrom":null},{"portName":"Announce","portId":1,"connectingTo":null,"connectedFrom":null}]},{"name":"Midi
Through","clientId":14,"ports":[{"portName":"Midi Through
Port-0","portId":0,"connectingTo":null,"connectedFrom":null}]},{"name":"USB
MIDI Controller","clientId":20,"ports":[{"portName":"USB MIDI Controller
MIDI 1","portId":0,"connectingTo":null,"connectedFrom":null}]},{"name":"USB
MIDI Interface","clientId":24,"ports":[{"portName":"USB MIDI Interface MIDI
1","portId":0,"connectingTo":null,"connectedFrom":null}]}]"

Mine isn't formatted nearly as nice as yours:
[image: image.png]

**Comment by sevenpoundowl** [comment]
Oops, just saw your email about the fix. Going ahead and trying that now.

**Comment by nuc** [comment]
The output looks good. 

Can you visit http://raspberrypi.local:3000/app with Chrome and check the console for errors?

**Comment by sevenpoundowl** [comment]
Unfortunately I am getting the same thing as before, just empty boxes. I
actually went ahead and reflashed my card with raspbian and started over
just to be sure I was doing it correctly.

**Comment by nuc** [comment]
Hmm, can you visit http://raspberrypi.local:3000/app with Chrome, hit
Cmd+Option+J to open the console, reload the app and check the output?

Are there any errors?

**Comment by sevenpoundowl** [comment]
[image: image.png]

I think I know what the problem is. I'm accessing the page at
http://192.168.1.219:3000/app instead of
http://raspberrypi.local:3000/app because
I have a bunch of pis on my network doing different things.

**Comment by sevenpoundowl** [comment]
Yeah, changing it so raspberrypi.local
<http://raspberrypi.local:3000/app> actually
pointed at that pi made it so the list populates properly.

**Comment by nuc** [comment]
Yeah, I was overly optimistic while using “raspberrypi.local” in the app.

I should make that configurable.

**Comment by CoolGames** [comment]
Same results here on laptop running Ubuntu studio instead of raspberry Pi.

My laptop is 

> MyLaptop.local

 and I have 3 Pi as mudpi (HDMI Pi 3+), blueberry Pi (headless Zero W in blue case) and MakeItPi (Headless Zero W with blinkt LED module).

I see the discussion but not a programmer so not sure where all the
url files need changing for each of my 4 systems.

I will be using with Scratch 3.0 re-written in Node.JS and not on Pi yet !

I am waiting for development of the Scratch external Midi extension so I wanted
 aconnect, aplaymidi and aplay for now in NodeJS, web server.
 
Please think of README explanations to allow use of npm instead of YARN on
regular Linux systems.

I am just learning to code NodeJS and Midi externals using Web Server so I understand
the concept but have yet to figure the flow through JS modules.

I am using this app to connect [Akai MPC mini Play ](https://www.akaipro.com/mpk-mini-play-mpkminiplay)
which has external general midi audio to built in speakers added to a popular mini 25 keyboard and [LPD8 pad controller](https://www.akaipro.com/lpd8-lpd8).
This will offload Midi sound and controller from Pi Zero eventually.

`1","portId":0,"connectingTo":null,"connectedFrom":null}]},{"name":"LPD8","clientId":24,"ports":[{"portName":"LPD8 MIDI 1","portId":0,"connectingTo":null,"connectedFrom":null}]},{"name":"MPK mini play","clientId":28,"ports":[{"portName":"MPK mini play MIDI `

**Comment by nuc** [comment]
Actually, the `raspberrypi.local` is not hardcoded anywhere, so everything should work by directly accessing the IP as well.

Cheers.

**Comment by nuc** [comment]
That's not true, the async requests had that name hardcoded. Apparently the fix is simple, removing that now.

**Comment by nuc** [comment]
@sevenpoundowl Please pull and restart. Should be fine now. Otherwise, feel free to reopen this issue.

Thanks.
